name: Lab 3 Grading

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Build and load image into Cluster
        run: |
          docker build -t ecommerce-app:local .
          kind load docker-image ecommerce-app:local --name kind

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
          sleep 10 

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh
